# Generated by Django 2.2.6 on 2020-09-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200905_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_img'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(max_length=255, verbose_name='Производитель'),
        ),
    ]
